
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_token TEXT;

UPDATE users SET is_verified = TRUE WHERE is_verified IS NULL;
